Remove settings plugin from tests project
Perhaps less valuable here, although some of these warnings deserve
a second look:

[error] slinky/tests/src/test/scala/slinky/core/ComponentTest.scala:186:71: parameter value prevState in value $anonfun is never used
[error]   override val getDerivedStateFromProps = (nextProps: Props, prevState: State) => {
[error]                                                                       ^
[error] slinky/tests/src/test/scala/slinky/core/ComponentTest.scala:207:71: parameter value prevState in value $anonfun is never used
[error]   override val getDerivedStateFromProps = (nextProps: Props, prevState: State) => {
[error]                                                                       ^
[error] slinky/tests/src/test/scala/slinky/core/ComponentTest.scala:224:45: parameter value e in value $anonfun is never used
[error]   override val getDerivedStateFromError = (e: js.Error) => {
[error]                                             ^
[error] slinky/tests/src/test/scala/slinky/core/ComponentTest.scala:344:74: parameter value r in value $anonfun is never used
[error]     val element: ReactElement = NoPropsComponent.withKey("hi").withRef((r: js.Object) => {})
[error]                                                                          ^
[error] slinky/tests/src/test/scala/slinky/core/ComponentTest.scala:394:66: parameter value error in value $anonfun is never used
[error]       ErrorBoundaryComponent(ErrorBoundaryComponent.Props(true, (error, info) => {
[error]                                                                  ^
[error] slinky/tests/src/test/scala/slinky/core/ComponentTest.scala:394:73: parameter value info in value $anonfun is never used
[error]       ErrorBoundaryComponent(ErrorBoundaryComponent.Props(true, (error, info) => {
[error]                                                                         ^
[error] slinky/tests/src/test/scala/slinky/core/ComponentTest.scala:407:67: parameter value error in value $anonfun is never used
[error]       ErrorBoundaryComponent(ErrorBoundaryComponent.Props(false, (error, info) => {
[error]                                                                   ^
[error] slinky/tests/src/test/scala/slinky/core/ComponentTest.scala:407:74: parameter value info in value $anonfun is never used
[error]       ErrorBoundaryComponent(ErrorBoundaryComponent.Props(false, (error, info) => {
[error]                                                                          ^
[error] slinky/tests/src/test/scala/slinky/core/ExternalComponentTest.scala:97:34: discarded non-Unit value
[error]       onClick := (e => { e.target: dom.html.Div }),
[error]                                  ^
[error] slinky/tests/src/test/scala/slinky/core/ExternalComponentTest.scala:98:23: discarded non-Unit value
[error]       ref := (e => { e: dom.html.Div})
[error]                       ^
[error] slinky/tests/src/test/scala/slinky/core/ExternalComponentTest.scala:7:35: Unused import
[error] import slinky.core.facade.{React, ReactElement}
[error]                                   ^
[error] slinky/tests/src/test/scala/slinky/core/FunctionalComponentTest.scala:6:35: Unused import
[error] import slinky.core.facade.{React, ReactElement}
[error]                                   ^
[error] slinky/tests/src/test/scala/slinky/core/HooksComponentTest.scala:229:19: pattern var dispatch in value $anonfun is never used; `dispatch@_' suppresses this warning
[error]       val (state, dispatch) = useReducer((s: String, a: Int) => {
[error]                   ^
[error] slinky/tests/src/test/scala/slinky/core/HooksComponentTest.scala:228:49: parameter value props in value $anonfun is never used
[error]     val component = FunctionalComponent[Unit] { props =>
[error]                                                 ^
[error] slinky/tests/src/test/scala/slinky/core/HooksComponentTest.scala:229:44: parameter value s in value $anonfun is never used
[error]       val (state, dispatch) = useReducer((s: String, a: Int) => {
[error]                                            ^
[error] slinky/tests/src/test/scala/slinky/core/HooksComponentTest.scala:355:48: parameter value props in value $anonfun is never used
[error]     val component = FunctionalComponent[Int] { props =>
[error]                                                ^
[info] slinky/tests/src/test/scala/slinky/core/ReaderWriterTest.scala:186:20: Using fallback derivation for type OpaqueClass (derivation: MacroReadersImpl)
[info]     readWrittenSame(new OpaqueClass(1), true)
[info]                    ^
[info] slinky/tests/src/test/scala/slinky/core/ReaderWriterTest.scala:186:20: Using fallback derivation for type OpaqueClass (derivation: MacroWritersImpl)
[info]     readWrittenSame(new OpaqueClass(1), true)
[info]                    ^
[info] slinky/tests/src/test/scala/slinky/core/ReaderWriterTest.scala:191:22: Using fallback derivation for type OpaqueClass (derivation: MacroReadersImpl)
[info]     assert(implicitly[Reader[Option[OpaqueClass]]].read(
[info]                      ^
[info] slinky/tests/src/test/scala/slinky/core/ReaderWriterTest.scala:191:22: Using fallback derivation for type OpaqueClass (derivation: MacroReadersImpl)
[info]     assert(implicitly[Reader[Option[OpaqueClass]]].read(
[info]                      ^
[info] slinky/tests/src/test/scala/slinky/core/ReaderWriterTest.scala:191:22: Using fallback derivation for type OpaqueClass (derivation: MacroReadersImpl)
[info]     assert(implicitly[Reader[Option[OpaqueClass]]].read(
[info]                      ^
[info] slinky/tests/src/test/scala/slinky/core/ReaderWriterTest.scala:192:17: Using fallback derivation for type OpaqueClass (derivation: MacroWritersImpl)
[info]       implicitly[Writer[Option[OpaqueClass]]].write(Some(new OpaqueClass(1)))
[info]                 ^
[info] slinky/tests/src/test/scala/slinky/core/ReaderWriterTest.scala:192:17: Using fallback derivation for type OpaqueClass (derivation: MacroWritersImpl)
[info]       implicitly[Writer[Option[OpaqueClass]]].write(Some(new OpaqueClass(1)))
[info]                 ^
[info] slinky/tests/src/test/scala/slinky/core/ReaderWriterTest.scala:192:17: Using fallback derivation for type OpaqueClass (derivation: MacroWritersImpl)
[info]       implicitly[Writer[Option[OpaqueClass]]].write(Some(new OpaqueClass(1)))
[info]                 ^
[info] slinky/tests/src/test/scala/slinky/core/ReaderWriterTest.scala:197:50: Using fallback derivation for type slinky.core.ContainingPrivateType.Test.type (derivation: MacroReadersImpl)
[info]     readWrittenSame[ContainingPrivateType.ToRead](ContainingPrivateType.TestInstance, true)
[info]                                                  ^
[info] slinky/tests/src/test/scala/slinky/core/ReaderWriterTest.scala:197:50: Using fallback derivation for type slinky.core.ContainingPrivateType.Test.type (derivation: MacroWritersImpl)
[info]     readWrittenSame[ContainingPrivateType.ToRead](ContainingPrivateType.TestInstance, true)
[info]                                                  ^
[error] slinky/tests/src/test/scala/slinky/core/ReaderWriterTest.scala:205:3: a pure expression does nothing in statement position; multiline expressions may require enclosing parentheses
[error]   {
[error]   ^
[error] slinky/tests/src/test/scala/slinky/core/ReaderWriterTest.scala:206:9: local method deriveReaderTypeclass in value <local ReaderWriterTest> is never used
[error]     def deriveReaderTypeclass[T: Reader]: Reader[T] = {
[error]         ^
[error] slinky/tests/src/test/scala/slinky/core/ReaderWriterTest.scala:210:9: local method deriveWriterTypeclass in value <local ReaderWriterTest> is never used
[error]     def deriveWriterTypeclass[T: Writer]: Writer[T] = {
[error]         ^
[error] slinky/tests/src/test/scala/slinky/core/ReaderWriterTest.scala:185:23: parameter value int in class OpaqueClass is never used
[error]     class OpaqueClass(int: Int)
[error]                       ^
[error] slinky/tests/src/test/scala/slinky/core/ReaderWriterTest.scala:190:23: parameter value int in class OpaqueClass is never used
[error]     class OpaqueClass(int: Int)
[error]                       ^
[error] <macro>:1:32: discarded non-Unit value
[error] { div(onMouseOver := (v => { (v: SyntheticMouseEvent[Element]) })) }
[error]                                ^
[error] <macro>:1:32: a pure expression does nothing in statement position
[error] { div(onMouseOver := (v => { (v: SyntheticMouseEvent[Element]) })) }
[error]                                ^
[error] slinky/tests/src/test/scala/slinky/core/TagTest.scala:79:28: discarded non-Unit value
[error]         onClick := (e => e.target),
[error]                            ^
[error] slinky/tests/src/test/scala/slinky/core/TagTest.scala:145:37: discarded non-Unit value
[error]     input(onInput := (v => v.target.value))(
[error]                                     ^
[error] slinky/tests/src/test/scala/slinky/core/TagTest.scala:11:40: Unused import
[error] import org.scalajs.dom.{Element, html, Event, MouseEvent}
[error]                                        ^
[error] slinky/tests/src/test/scala/slinky/core/TagTest.scala:11:47: Unused import
[error] import org.scalajs.dom.{Element, html, Event, MouseEvent}
[error]                                               ^
[error] slinky/tests/src/test/scala/slinky/core/TagTest.scala:31:9: local val foo in value <local TagTest> is never used
[error]     val foo: Seq[ReactElement] = Seq(div(), a())
[error]         ^
[error] slinky/tests/src/test/scala/slinky/core/TagTest.scala:157:9: local val fullyBuilt in value <local TagTest> is never used
[error]     val fullyBuilt: ReactElement = halfBuilt("hi")
[error]         ^
[error] slinky/tests/src/test/scala/slinky/core/TagTest.scala:160:11: local val fullyBuilt2 in value <local TagTest> is never used
[error]       val fullyBuilt2: ReactElement = halfBuilt("hi2")
[error]           ^
[error] slinky/tests/src/test/scala/slinky/core/TagTest.scala:80:17: parameter value r in value $anonfun is never used
[error]         ref := (r => {})
[error]                 ^
[error] slinky/tests/src/test/scala/slinky/core/annotations/ReactAnnotatedComponentTest.scala:313:74: parameter value r in value $anonfun is never used
[error]     val element: ReactElement = NoPropsComponent.withKey("hi").withRef((r: js.Object) => {})
[error]                                                                          ^
[error] slinky/tests/src/test/scala/slinky/core/annotations/ReactAnnotatedComponentTest.scala:335:37: parameter value error in value $anonfun is never used
[error]       ErrorBoundaryComponent(true, (error, info) => {
[error]                                     ^
[error] slinky/tests/src/test/scala/slinky/core/annotations/ReactAnnotatedComponentTest.scala:335:44: parameter value info in value $anonfun is never used
[error]       ErrorBoundaryComponent(true, (error, info) => {
[error]                                            ^
[error] slinky/tests/src/test/scala/slinky/core/annotations/ReactAnnotatedComponentTest.scala:348:38: parameter value error in value $anonfun is never used
[error]       ErrorBoundaryComponent(false, (error, info) => {
[error]                                      ^
[error] slinky/tests/src/test/scala/slinky/core/annotations/ReactAnnotatedComponentTest.scala:348:45: parameter value info in value $anonfun is never used
[error]       ErrorBoundaryComponent(false, (error, info) => {
[error]                                             ^
[error] 36 errors found
[error] (Test / compileIncremental) Compilation failed